# Architecture.
z_dim: 3
channels: [64, 128, 256, 512]
mid_channels: [512, 512]
change_res: [True, True, True]
time_dim: 256
num_res_layers: 2
num_heads: 8
num_groups: 32
num_classes: 7
cond_drop_prob: 0.1

# Noise.
num_steps: 1000
beta_start: 0.0001
beta_end: 0.02
offset: 8e-3

# Training.
learning_rate: 5e-6 #2.25e-5 # 
batch_size: 24
total_epochs: 50
epochs: 50
clip_grad: 1.0
precision: fp32

# Util.
train_set: ./data/diffusion/train.npy
train_labels: ./data/diffusion/classes_train.npy
plot_set: ./data/plot.npy
checkpoints_dir: ./checkpoints
logs_dir: ./logs
seed: 2018
log_imgs_freq: 1000