# Architecture
in_channels: 3
channels: [128, 256, 384]
enc_num_res_blocks: 2
dec_num_res_blocks: 2
attn_resolutions: [] 
num_heads: 1
bottleneck: kl
codebook_size: null
codebook_beta: null
codebook_gamma: null
disc_channels: [64, 128, 256]
z_dim: 3
init_resolution: 128
num_groups: 32

# Training
recon_weight: 1.0
percept_weight: 1.0
prior_weight: 5e-6
disc_weight: 0.1
disc_start: 15000
gan_loss: "bce" # "bce", "mse" or "hinge"
learning_rate: 1e-5
warmup_steps: 0
batch_size: 24
epochs: 15
clip_grad: 1.0
precision: fp16
compile: true

# Util
train_set: ./data/vqgan/train.npy
dev_set: ./data/vqgan/dev.npy
plot_set: ./data/vqgan/plot.npy
checkpoints_dir: ./checkpoints
logs_dir: ./logs
seed: 2018
log_imgs_freq: 500
log_interval: 50